interface Subject {
  name: string
  maxMarks: number
  score: number
}

const getSubjectName = (subjectName: string, language: string) => {
  // Always use English names in PDF for better compatibility
  switch (subjectName) {
    case 'english': return 'English'
    case 'arabic': return 'Arabic'
    case 'islamic': return 'Islamic'
    case 'history': return 'History'
    default: return subjectName
  }
}

export const generatePDF = async (subjects: Subject[], result: { totalScore: number; percentage: number }, language: string, studentName: string) => {
  // Dynamically import jsPDF to avoid build issues
  const { jsPDF } = await import('jspdf')
  
  const doc = new jsPDF()
  
  // For Arabic support, we'll use a different approach
  // Since Arabic fonts are complex to embed, we'll use English labels but keep Arabic content where needed
  
  // Title
  const title = 'Tawjihi Result Certificate'
  doc.setFontSize(24)
  doc.setFont('helvetica', 'bold')
  doc.text(title, 105, 20, { align: 'center' })
  
  // Website branding
  doc.setFontSize(12)
  doc.setFont('helvetica', 'normal')
  const website = 'tawjihi-calculator.vercel.app'
  doc.text(website, 105, 30, { align: 'center' })
  
  // Line separator
  doc.line(20, 35, 190, 35)
  
  // Student name
  doc.setFontSize(14)
  doc.setFont('helvetica', 'bold')
  const nameLabel = 'Student Name:'
  doc.text(nameLabel, 30, 50)
  doc.setFont('helvetica', 'normal')
  doc.text(studentName, 80, 50)
  
  // Date
  const dateLabel = 'Date:'
  doc.setFont('helvetica', 'bold')
  doc.text(dateLabel, 30, 65)
  doc.setFont('helvetica', 'normal')
  const currentDate = new Date().toLocaleDateString()
  doc.text(currentDate, 80, 65)
  
  // Table header
  doc.setFontSize(12)
  doc.setFont('helvetica', 'bold')
  doc.text('Subject', 30, 85)
  doc.text('Score', 120, 85)
  doc.text('Max', 150, 85)
  doc.text('Percentage', 170, 85)
  
  // Table line
  doc.line(20, 90, 190, 90)
  
  // Subject scores in table format
  doc.setFont('helvetica', 'normal')
  let yPosition = 105
  
  subjects.forEach((subject) => {
    const subjectName = getSubjectName(subject.name, language)
    const score = subject.score.toString()
    const maxMarks = subject.maxMarks.toString()
    const percentage = ((subject.score / subject.maxMarks) * 100).toFixed(1) + '%'
    
    doc.text(subjectName, 30, yPosition)
    doc.text(score, 120, yPosition)
    doc.text(maxMarks, 150, yPosition)
    doc.text(percentage, 170, yPosition)
    yPosition += 10
  })
  
  // Total row
  doc.line(20, yPosition + 2, 190, yPosition + 2)
  yPosition += 10
  
  doc.setFont('helvetica', 'bold')
  const totalLabel = 'Total'
  const totalScore = result.totalScore.toString()
  const totalMax = '300'
  const totalPercentage = ((result.totalScore / 300) * 100).toFixed(1) + '%'
  
  doc.text(totalLabel, 30, yPosition)
  doc.text(totalScore, 120, yPosition)
  doc.text(totalMax, 150, yPosition)
  doc.text(totalPercentage, 170, yPosition)
  
  // Final percentage result
  yPosition += 20
  doc.setFontSize(16)
  doc.setFont('helvetica', 'bold')
  const finalLabel = 'First Year Percentage (30%)'
  const finalPercentage = `${result.percentage.toFixed(2)}%`
  
  doc.text(finalLabel, 30, yPosition)
  doc.text(finalPercentage, 150, yPosition)
  
  // Contact information
  yPosition += 30
  doc.setFontSize(12)
  doc.setFont('helvetica', 'bold')
  const contactLabel = 'Contact Information:'
  doc.text(contactLabel, 30, yPosition)
  
  yPosition += 10
  doc.setFont('helvetica', 'normal')
  doc.text('Developer: Abdlarahman Alshabatat', 30, yPosition)
  
  yPosition += 8
  doc.text('Email: ashbatat@gmail.com', 30, yPosition)
  
  yPosition += 8
  doc.text('Phone: +962 79 088 1392', 30, yPosition)
  
  // Website information
  yPosition += 15
  doc.setFont('helvetica', 'bold')
  const websiteLabel = 'Visit our website:'
  doc.text(websiteLabel, 30, yPosition)
  
  yPosition += 8
  doc.setFont('helvetica', 'normal')
  doc.text(website, 30, yPosition)
  
  // Footer
  doc.setFontSize(10)
  doc.setFont('helvetica', 'normal')
  const footer = 'Generated by Tawjihi Calculator - Developed by Abdlarahman Alshabatat'
  doc.text(footer, 105, 270, { align: 'center' })
  
  // Save the PDF
  doc.save(`tawjihi-result-${studentName}-${Date.now()}.pdf`)
}
